## Contour Plots

A contour plot is a graphical representation of a 3D object in 2D. It shows lines that connect points of equal value (also known as level curves). For example, for a function \( $f(x, y) = x^2 + y^2$ \), a contour plot would show curves where the function value is constant, giving a sense of the surface's shape. That is the contours will be defined by $C_n = x^2 + y^2$, where $C_n$ is the $n^{th}$ contour.

In this notebook, we'll plot the 2D parabola \( f(x, y) = x^2 + y^2 \) using contour plots. We'll also cover how to customize and make this plot more informative and visually appealing.


### 1. Importing the necessary libraries

Again, we will need `numpy` and `matplotlib`.


In [1]:
# Importing necessary libraries
import numpy as np
import matplotlib.pyplot as plt

### 2. Setting up the 2D Grid

To create a contour plot, we need a grid of `x` and `y` values. We'll use `np.meshgrid()` to generate two 2D arrays: one for the `x` coordinates and one for the `y` coordinates. This allows us to evaluate the function \( $f(x, y) = x^2 + y^2 $\) at every point in the grid.

We’ll use `np.linspace()` to generate a range of evenly spaced points for both `x` and `y`. These values will define the domain of the function.


In [4]:
# Define the range for x and y values
x = np.linspace(-5, 5, 5)
y = np.linspace(-5, 5, 5)

# Create a grid of x and y values
X, Y = np.meshgrid(x, y)

# Display the x, and y values, and the meshgrid and its shape
print("x-values:\n", x)
print("y-values:\n", y)
print("")
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)
print("")
print("Output of meshgrid for X:\n", X)
print("Output of meshgrid for Y:\n", Y)

x-values:
 [-5.  -2.5  0.   2.5  5. ]
y-values:
 [-5.  -2.5  0.   2.5  5. ]

Shape of X: (5, 5)
Shape of Y: (5, 5)

Output of meshgrid for X:
 [[-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]]
Output of meshgrid for Y:
 [[-5.  -5.  -5.  -5.  -5. ]
 [-2.5 -2.5 -2.5 -2.5 -2.5]
 [ 0.   0.   0.   0.   0. ]
 [ 2.5  2.5  2.5  2.5  2.5]
 [ 5.   5.   5.   5.   5. ]]


### 3. Defining the 2D Parabola Function

The equation of a 2D parabola is given by:

\[
$f(x, y) = x^2 + y^2$
\]

We will now calculate the `z` values for each pair of `x` and `y` values in the grid, which will represent the height of the parabola at each point.


In [5]:
# Define the 2D parabola function
Z = X**2 + Y**2

# Display the Z array to confirm the values
print("meshgrid for X:\n", X)
print("meshgrid for Y:\n", Y)
print("function called on X, Y values:\n", Z)


meshgrid for X:
 [[-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]]
meshgrid for Y:
 [[-5.  -5.  -5.  -5.  -5. ]
 [-2.5 -2.5 -2.5 -2.5 -2.5]
 [ 0.   0.   0.   0.   0. ]
 [ 2.5  2.5  2.5  2.5  2.5]
 [ 5.   5.   5.   5.   5. ]]
function called on X, Y values:
 [[50.   31.25 25.   31.25 50.  ]
 [31.25 12.5   6.25 12.5  31.25]
 [25.    6.25  0.    6.25 25.  ]
 [31.25 12.5   6.25 12.5  31.25]
 [50.   31.25 25.   31.25 50.  ]]


In [6]:
print(np.transpose([X.flatten(), Y.flatten(), Z.flatten()]))

[[-5.   -5.   50.  ]
 [-2.5  -5.   31.25]
 [ 0.   -5.   25.  ]
 [ 2.5  -5.   31.25]
 [ 5.   -5.   50.  ]
 [-5.   -2.5  31.25]
 [-2.5  -2.5  12.5 ]
 [ 0.   -2.5   6.25]
 [ 2.5  -2.5  12.5 ]
 [ 5.   -2.5  31.25]
 [-5.    0.   25.  ]
 [-2.5   0.    6.25]
 [ 0.    0.    0.  ]
 [ 2.5   0.    6.25]
 [ 5.    0.   25.  ]
 [-5.    2.5  31.25]
 [-2.5   2.5  12.5 ]
 [ 0.    2.5   6.25]
 [ 2.5   2.5  12.5 ]
 [ 5.    2.5  31.25]
 [-5.    5.   50.  ]
 [-2.5   5.   31.25]
 [ 0.    5.   25.  ]
 [ 2.5   5.   31.25]
 [ 5.    5.   50.  ]]


### 4. Creating a Basic Contour Plot

Let's now create a contour plot of the function \( $f(x, y) = x^2 + y^2$ \).

We will:
- Use `plt.contour()` for contour lines or `plt.contourf()` for filled contours.
- Add a color bar to visually represent the function values.

Note: 
- I am using the `'viridis'` `colormap`
- You can see the colormaps available using `print(plt.colormaps())`
- You can explore them at the [MatPlotLib Colormap Reference](https://matplotlib.org/stable/gallery/color/colormap_reference.html)

In [ ]:
# Create the contour plot
plt.figure(figsize=(6, 5))
contour = plt.contour(X, Y, Z,
                      levels=10,
                      cmap='viridis')  # Use contour lines with 10 levels
plt.colorbar(contour)  # Add a color bar
plt.title('Contour Plot of $x^2 + y^2$')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Show the plot
plt.show()


We need more points to make this looks correct. Let's add them now.

In [ ]:
# Define the range for x and y values
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)

# Create a grid of x and y values
X, Y = np.meshgrid(x, y)

# Define the 2D parabola function
Z = X**2 + Y**2

Now we can replot the contour plot with the updated values

In [7]:
# Create the contour plot
plt.figure(figsize=(6, 5))
contour = plt.contour(X, Y, Z,
                      levels=10,
                      cmap='viridis')  # Use contour lines with 10 levels
plt.colorbar(contour)  # Add a color bar
plt.title('Contour Plot of $x^2 + y^2$')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Show the plot
plt.show()

### 5. Adding Labels and Titles

To make the plot more informative, we will add:
- **X-axis and Y-axis labels** to describe what each axis represents.
- **A title** to give an overview of the plot’s content.
- **A color bar label** to explain the range of values for the contour levels.

We can do this using:
- `plt.xlabel('label text')`: Adds a label to the X-axis.
- `plt.ylabel('label text')`: Adds a label to the Y-axis.
- `plt.title('title text')`: Adds a title to the plot.

Here we use `plt.contourf` to make filled contours. 


In [ ]:
# Create the contour plot
plt.figure(figsize=(6, 5))
contour = plt.contourf(X, Y, Z, levels=10, cmap='viridis')  # Filled contour plot
cbar = plt.colorbar(contour)  # Add a color bar
cbar.set_label('Energy (arbitrary units)', fontsize=12)  # Label for the color bar

# Add labels and title
plt.title('Potential Energy of 2D Harmonic Oscillator', fontsize=14)
plt.xlabel('X-dispalcement (arbitrary units', fontsize=12)
plt.ylabel('Y-displacement (arbitrary units)', fontsize=12)

# Show the plot
plt.show()


### 6. Customizing the Contour Plot

There are several ways we can customize a contour plot to make it more informative and visually appealing:
- **Contour Levels**: Control the number of contour levels using the `levels` argument.
- **Colormap**: Customize the colormap using `cmap`.
- **Line Styles**: For contour lines, adjust the line styles (solid, dashed, etc.) using `linestyles`.

We can modify these properties to fit the needs of the plot.


In [ ]:
# Customizing the contour plot with more levels and a different colormap

plt.figure(figsize=(6, 5))

# Use contour lines instead of filled contours and increase the number of levels
contour = plt.contour(X, Y, Z, levels=20, cmap='plasma', linestyles='--')  # Dashed lines with 20 levels
cbar = plt.colorbar(contour)  # Add a color bar
cbar.set_label('Energy (arbitrary units)', fontsize=12)  # Custom label for the color bar

# Add labels and title
plt.title('Potential Energy of 2D Harmonic Oscillator (Customized)', fontsize=14)
plt.xlabel('X-displacement (arbitrary units)', fontsize=12)
plt.ylabel('Y-displacement (arbitrary units)', fontsize=12)

# Show the plot
plt.show()


### 7. Adding Gridlines and Setting Axis Limits

Gridlines can help make the plot more readable by providing reference points along the axes. Additionally, we can set limits on the x and y axes to zoom in or focus on a specific region of the plot.

We will:
- Add gridlines using `plt.grid(True)`.
- Set the axis limits using `plt.xlim([xmin, xmax])` and `plt.ylim([ymin, ymax])`.


In [ ]:
# Customizing the plot with gridlines and axis limits

plt.figure(figsize=(6, 5))

# Create the contour plot with more levels and a different colormap
contour = plt.contourf(X, Y, Z, levels=15, cmap='viridis')
cbar = plt.colorbar(contour)
cbar.set_label('Energy (arbitrary units)', fontsize=12)

# Add labels and title
plt.title('Potential Energy of 2D Harmonic Oscillator', fontsize=14)
plt.xlabel('X-displacement (arbitrary units)', fontsize=12)
plt.ylabel('Y-displacement (arbitrary units)', fontsize=12)

# Add gridlines
plt.grid(True)

# Set axis limits
plt.xlim([-4, 4])
plt.ylim([-4, 4])

# Show the plot
plt.show()


### 8. Specifying Contours by Their Constant Value

In some cases, you may want to specify exact contour levels instead of automatically generating them. You can provide a list of contour levels (constant values) directly in the `levels` argument.

For example, if you want to display contours at specific function values (e.g., 1, 4, 9, 16, 25), you can pass these values in the `levels` argument.

Additionally, you may want to have a contour labeled with its value. You can use `plt.clabel` to help with that.


In [ ]:
# Specify constant contour values
contour_levels = [0, 0.5, 1, 22, 25]  # Define the contour levels you want to display

plt.figure(figsize=(5, 5))

# Create the contour plot using the specified contour levels
contour = plt.contour(X, Y, Z, levels=contour_levels, linestyles='--', linewidths=0.5, colors='red')

# Add labels and title
plt.title('Potential Energy of 2D Harmonic Oscillator', fontsize=14)
plt.xlabel('X-displacement (arbitrary units)', fontsize=12)
plt.ylabel('Y-displacement (arbitrary units)', fontsize=12)

# Add labels to the contour lines
plt.clabel(contour, inline=True, fontsize=10)  # fmt='%1.0f' ensures integer labels

# Add gridlines
plt.grid(True)

# Set axis limits
plt.xlim([-5.5, 5.5])
plt.ylim([-5.5, 5.5])

# Show the plot
plt.show()


### Creating a Reusable Contour Plot Function

To make it easy to generate contour plots, we will wrap the functionality into a reusable Python function. This function will allow you to:
- Plot contour lines for any function of `X` and `Y`.
- Specify custom contour levels, line width, and color.
- Add labels to contour lines.
- Customize axis labels, title, gridlines, and axis limits.

You can call this function with different data and parameters to generate contour plots quickly and consistently.


In [ ]:
def plot_contours(X, Y, Z, contour_levels, title='Contour Plot', xlabel='X-axis', ylabel='Y-axis',
                  fill_color_map='viridis', line_color='black', line_width=1, add_labels=True, grid=True,
                  xlim=None, ylim=None, add_colorbar=True, figsize=(6, 5)):
    """
    Function to plot filled contour lines with optional superimposed labeled contours and an optional color bar.

    Parameters:
    - X, Y: 2D arrays for the grid points (from np.meshgrid)
    - Z: 2D array of function values (e.g., f(x, y) = x^2 + y^2)
    - contour_levels: List of contour levels to display
    - title: Title of the plot
    - xlabel: Label for the X-axis
    - ylabel: Label for the Y-axis
    - fill_color_map: Colormap for the filled contours (default is 'viridis')
    - line_color: Color of the contour lines (default is black)
    - line_width: Width of the contour lines (default is 1)
    - add_labels: Whether to label the contour lines (default is True)
    - grid: Whether to add gridlines (default is True)
    - xlim: Tuple for x-axis limits (e.g., (-5, 5))
    - ylim: Tuple for y-axis limits (e.g., (-5, 5))
    - add_colorbar: Whether to add a color bar (default is True)
    """
    plt.figure(figsize=figsize)
    
    # Create the filled contour plot with the specified color map
    contour_filled = plt.contourf(X, Y, Z, levels=contour_levels, cmap=fill_color_map)
    
    # Optionally create the contour lines with specified levels, line color, and line width
    if add_labels:
        contour_lines = plt.contour(X, Y, Z, levels=contour_levels, colors=line_color, linewidths=line_width)
        plt.clabel(contour_lines, inline=True, fontsize=10, fmt='%1.0f')
    
    # Add title and axis labels
    plt.title(title, fontsize=14)
    plt.xlabel(xlabel, fontsize=12)
    plt.ylabel(ylabel, fontsize=12)
    
    # Optionally add a color bar to show the mapping of values to colors
    if add_colorbar:
        cbar = plt.colorbar(contour_filled)
        cbar.set_label('Function value', fontsize=12)
    
    # Optionally add gridlines
    if grid:
        plt.grid(True)
    
    # Set axis limits if specified
    if xlim:
        plt.xlim(xlim)
    if ylim:
        plt.ylim(ylim)
    
    # Show the plot
    plt.show()



In [ ]:
# Define contour levels
contour_levels = [0, 1, 4, 9, 16, 25, 50]

# Call the updated function to plot filled contours with labeled contour lines
plot_contours(X, Y, Z, contour_levels, title='', 
              xlabel='X-displacement (arbitrary units)', ylabel='Y-displacement (arbitrary units)', 
              fill_color_map='viridis', line_width=0.5, grid=False, add_colorbar=False, figsize=[5,5])


### Summary

In this notebook, we explored how to create **contour plots** using `matplotlib`. Contour plots are a nice way to visualize 3D data in 2D space by representing lines of constant values. We used the following approaches:
- **Filled Contours** using `plt.contourf()`.
- **Labeled Contours** using `plt.contour()` and `plt.clabel()` for better clarity of the plot.
- **Customizable Plot Properties**: including colormaps, axis labels, gridlines, color bars, and more.
- **Reusable Function**: We created a function that encapsulates all these options, making it easier to reuse for different datasets.

Additionally, you can make 3D plots using `plot_surface()` for visualizing data in true three dimensions. We might get to this later in the class.

### Where to Learn More
To dive deeper into contour and 3D plotting with `matplotlib`, check out the following resources:
- **Matplotlib Documentation on Contour Plots**: [Contour and Filled Contour Plots](https://matplotlib.org/stable/gallery/images_contours_and_fields/contourf_demo.html)
- **Matplotlib 3D Plotting Documentation**: [3D plotting in Matplotlib](https://matplotlib.org/stable/gallery/mplot3d/index.html)
- **Numpy for Data Generation**: [Numpy Meshgrid and Linspace](https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html)

The goal is to use these tools to create insightful figures to communicate your understanding of problems concisely. We'll continue to work on that throughout the class